### ISSUE TITLE
不能调节亮度

### ISSUE THREAD

**Issue by leungzengzeng** [JokerHYC/P775TM-HACKINTOSH#1]
你好,很感谢你分享的CLOVER,我的笔记本是GX8CP7S2,根据你的教程使用黑果小兵10.13.6 17G65的镜像替换我的efi进行安装.系统安装完成后安装Nvdia显卡驱动.安装完以后,基本完美,暂时发现不能亮度调节,不能使用耳机和无法插上鼠标关闭触控板(设置了,不起作用),睡眠时间设置不起作用,麻烦指导下这两个问题该怎么解决,方便留一个联系方式吗?谢了

**Comment by JokerHYC** [comment]
亮度我也没搞定.
鼠标插入关闭触控板我搞定了 回头更新一下.
睡眠设置不起作用你要切换一下机型才行,设置成MacBook机型设置完再切回去 或者彻底就用MacBook pro机型即可.

**Comment by JokerHYC** [comment]
更新了一下efi 最新的config是睡眠时间设置ok的.
