### ISSUE TITLE
我装了webdriver ，然后重启到输密码就操控不了，还会黑屏

### ISSUE THREAD

**Issue by 1205129045x** [JokerHYC/P775TM-HACKINTOSH#11]
是不是装了webdriver后要改efi里面的参数

**Comment by JokerHYC** [comment]
webdriver 一定要和系统版本对应。 不同的话就会出现这种情况。

**Comment by 1205129045x** [comment]
> webdriver 一定要和系统版本对应。 不同的话就会出现这种情况。

我用的是17g65，下载的webdriver也是对应的驱动WebDriver-387.10.10.10.40.105.pkg

**Comment by 1205129045x** [comment]
弄好了 谢谢大佬，我是p755 gtx1070 能用
外接显示器，想用显示器的喇叭，笔记本的喇叭能用，音量那里选数码输出，但是调音量大小的滑动栏是灰色的

**Comment by JokerHYC** [comment]
显示器的喇叭走得是nv的驱动，那没辙。 第二个音频输出口是很完美的。 喇叭也没问题。

**Comment by 1205129045x** [comment]
> 显示器的喇叭走得是nv的驱动，那没辙。 第二个音频输出口是很完美的。 喇叭也没问题。

那个3.5毫米耳机口是能用的吗

**Comment by 1205129045x** [comment]
我还申请加群了，好像没通过

**Comment by JokerHYC** [comment]
耳机接口是ok的。 群？ 蓝天准群？ 638463408？ 我不是管理。
