### ISSUE TITLE
更新后,进不了系统了

### ISSUE THREAD

**Issue by leungzengzeng** [JokerHYC/P775TM-HACKINTOSH#2]
![微信图片_20191114090821](https://user-images.githubusercontent.com/11469337/68817998-7386fa00-06be-11ea-9949-03bff1caba4f.jpg)
更新后,开机出现这个图标,然后就关机了,然后我单独替换config.plist文件也是不管用,还遇到一个莫名其妙的事情,我重新下载的上个版本的EFI,竟然也进不去系统,必须用我上次下载的2019.10.21版本.问一个比较小白的问题,直接替换EFI需要重装系统吗?

**Comment by JokerHYC** [comment]
检查bios设置 
secure boot关闭 
ahci模式开启
vt-d关闭
然后启动参数加上-v看看具体报错再说

**Comment by leungzengzeng** [comment]
在clover的boot参数里添加-no_compat_check可以进系统

**Comment by JokerHYC** [comment]
如果bios版本太老建议省级EC和BIOS,不想升级的话添加no_compat_check到boot args
