### ISSUE TITLE
10.15.3 无法驱动独立显卡

### ISSUE THREAD

**Issue by cqboyone** [JokerHYC/P775TM-HACKINTOSH#4]
我笔记本型号是GX8 SP7S1 ,模具是P775DM2 . 之前是10.13.6能驱动显卡,现在升级成10.15.3无法安装显卡驱动了

**Comment by MJfanszzw** [comment]
N卡最高10.13.6




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cqboyone"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月27日(星期四) 凌晨0:12
收件人:&nbsp;"JokerHYC/P775TM-HACKINTOSH"<P775TM-HACKINTOSH@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JokerHYC/P775TM-HACKINTOSH] 10.15.3 无法驱动独立显卡 (#4)




我笔记本型号是GX8 SP7S1 ,模具是P775DM2 . 之前是10.13.6能驱动显卡,现在升级成10.15.3无法安装显卡驱动了
