### ISSUE TITLE
老哥,这个楼主是安装成功最新的系统吗

### ISSUE THREAD

**Issue by conkyliu** [JokerHYC/P775TM-HACKINTOSH#6]
https://www.insanelymac.com/forum/topic/343254-need-help-to-install-asus-rog-strix-z370-e-gaming-i9-9900k-and-gtx-1070/

**Comment by JokerHYC** [comment]
人家是用的核显装的.
相当于屏蔽了独显.
775已经屏蔽了核显,无法操作.
