### ISSUE TITLE
希望早点出oc引导 远景论坛已经有一个efi啦 只要把网卡驱动换一下就好啦 那个是1820A的网卡

### ISSUE THREAD

**Issue by izyq** [JokerHYC/P775TM-HACKINTOSH#8]
http://bbs.pcbeta.com/viewthread-1848212-1-1.html 这是远景帖子地址 可以参考一下哦

**Comment by Zmastet** [comment]
http://bbs.pcbeta.com/viewthread-1848212-1-1.html  这是远景帖子地址 可以参考一下哦

**Comment by JokerHYC** [comment]
反正也只能13.6了 懒得折腾了 你可以搞一下.

**Comment by FreeManxuyang** [comment]
大佬，这个efi里面有驱动，是不是直接装这些驱动就可以了？不懂，求教

**Comment by JokerHYC** [comment]
> 大佬，这个efi里面有驱动，是不是直接装这些驱动就可以了？不懂，求教

这个efi是直接带了1560的驱动,你如果是1820a可以试着替换一下就行了.

**Comment by 1205129045x** [comment]
> http://bbs.pcbeta.com/viewthread-1848212-1-1.html 这是远景帖子地址 可以参考一下哦

efi能分享下吗
